# Generated by Django 4.1.5 on 2023-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
