# Generated by Django 4.1.5 on 2023-01-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
